### ISSUE TITLE
My Books takes too long to show generated covers with poor internet connection

### ISSUE THREAD

**Issue by ghost** [NYPL-Simplified/Simplified-iOS#154]
My Books will try to load a cover it doesn't have over the network. During this time, the cover will simply be blank—and that time can be quite long if the internet connection is poor. It will do this even if the book has no cover on the server (because it has no way to know otherwise), so what happens is that the user simply has to wait to see the generated cover they're going to have to see anyway.

What should happen is that My Books—and Catalog too, if it doesn't already—should show a generated cover until a real cover eventually shows up.

**Comment by gioneill** [comment]
Will not fix.
