### ISSUE TITLE
Verify correct timeout when retrieving search results

### ISSUE THREAD

**Issue by ghost** [NYPL-Simplified/Simplified-iOS#182]

**Comment by leonardr** [comment]
We get a very large number of patron complaints about connectivity issues on networks that are slow but not unusable slow. It seems to happen exclusively on iOS, and especially when doing search. Ask NYPL is swamped by these issues and has no way of resolving them.

**Comment by gioneill** [comment]
A number of issues have been addressed that should overall significantly improve the user-experience under various "slow or inconsistent (but still usable)" network connections.

Specifically for searching, I've been able to confirm that a search will not timeout even under very poor network conditions of 10% packet loss and a downspeed less than 1 mbps.

Unchanged behavior: the list of books will present immediately, while the cover images load and fill in asynchronously.

**Comment by leonardr** [comment]
Thanks for working on this!
