### ISSUE TITLE
3-finger flick left or right should advance pages

### ISSUE THREAD

**Issue by raduzb** [NYPL-Simplified/Simplified-iOS#223]
(with VoiceOver ON)

3 finger gestures
Swipe left or right Move to previous or next horizontal screen/page
Swipe up or down    Move/scroll down or up (like moving a paper)

This is how it is done in iBooks and is described in Apple's accessbility documentation. But generally it's nearly impossible to advance pages with any gestures. sometimes double tapping text advances pages, but sometimes it brings up or dismisses the reader UI. it seems to be quite random and different for different books. 

The user should be able to use the standard 3 fingers swipe left/right or up/down to scroll. (This could be a Readium or Readium integration limitation as well)

**Comment by winniequinn** [comment]
We're going to be fixing this with Readium 2! I would not expect progress on this issue until then though.

**Comment by winniequinn** [comment]
This has been completed, or at least as much as it can be before we move to Readium 2.
