### ISSUE TITLE
Review current state of syncing

### ISSUE THREAD

**Issue by ghost** [NYPL-Simplified/Simplified-iOS#252]
It sounds like certain things have changed in my absence and I really need to come up to speed on this! I'm going to take some time to review and document things as appropriate given that it's the trickiest part of the app.

**Comment by aferditamuriqi** [comment]
@winniequinn is this still a review thing? or an issue?

**Comment by winniequinn** [comment]
To me it would be because I'm not sure of the current state of syncing in the app. I personally would need to review it before I could give it my stamp of approval. If you have confidence in it as it is now though then you can certainly go ahead and close this!

**Comment by aferditamuriqi** [comment]
I am not sure what was supposed to be reviewed here, we can keep this ticket as is then until you get to review.
