### ISSUE TITLE
Gather patron username when applying for card

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#267]
We made this change to the web app and now it needs to be reflected in the mobile app. When a patron applies for a card there's now an additional step in which they choose their username. Use the web app and talk with Matthew for guidance.

I'll update this issue with more requirements as we get them. For instance, we may want to set the patron's email address as their default username, or username may turn out not to be required.

**Comment by aferditamuriqi** [comment]
this seems to be not needed anymore, as we have implemented the card creator.
