### ISSUE TITLE
Retrieve username and barcode

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#268]
https://github.com/NYPL/Simplified-circulation/issues/24 will establish a new API endpoint that serves detailed information about a patron.

Client software needs to know how to fetch this info, process it, and store it locally until the patron logs out.

As a motivating case, if the patron logs on with their NYPL username, then goes to look at their settings, this new controller is how you find out what their barcode is. And vice versa if the patron logs on with their barcode.

**Comment by winniequinn** [comment]
Any idea on the status of this, @gioneill?

**Comment by leonardr** [comment]
We now send the patron's authorization identifier in an extension tag in the loans feed, not through a separate endpoint.
