### ISSUE TITLE
Fix title color and font for help desk

### ISSUE THREAD

**Issue by ghost** [NYPL-Simplified/Simplified-iOS#278]

**Comment by aferditamuriqi** [comment]
this seems to be completed already,.

<img src="https://cloud.githubusercontent.com/assets/17150623/24068783/05c3ddd8-0b6e-11e7-80a5-b87dab9690b2.png" width="200px"/><img src="https://cloud.githubusercontent.com/assets/17150623/24068784/05cbe0f0-0b6e-11e7-80a1-69543aa53994.png" width="200px"/><img src="https://cloud.githubusercontent.com/assets/17150623/24068785/05cd8c20-0b6e-11e7-984d-cae186b1d922.png" width="200px"/>
