### ISSUE TITLE
Fix crash in card signup flow

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#299]
From Bugsnag:

NSInvalidArgumentException·-[CLLocationManager requestLocation]: unrecognized selector sent to instance 0x18376680
/Users/winnie/Documents/NYPL/Git/Simplified-iOS/Simplified/NYPLLocationCardController.m:137-[NYPLLocationCardController setIsDeterminingLocation:]	
 Simplified:0-[UIApplication(EventInterceptor) heap_sendAction:to:from:forEvent:]	
 Simplified:0-[UIApplication(EventInterceptor) heap_sendEvent:]

**Comment by aferditamuriqi** [comment]
Closing this issue, as it is outdated and referee to the previous card creation
