### ISSUE TITLE
Help desk display is not handled correctly

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#300]
In particular, `viewController` can be uninitialized garbage on line `NYPLSettingsSplitViewController.m:73`.

**Comment by aferditamuriqi** [comment]
this is being addressed here https://github.com/NYPL-Simplified/Simplified-iOS/issues/488

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
