### ISSUE TITLE
In-text links often don't work

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#312]
I've only seen this on Open Ebooks, but I suspect it's a general problem.

I checked out a book on Open Ebooks, let's say "1 Shot" by Susan Glick or "Gullivers Travels" from the open-access collection. These books present their table of contents as a list of links in the body of the book. If I tap on one of those links I'm taken briefly to the appropriate section of the book, but then I'm taken right back to the table of contents.

The same links are available from the drop-down table of contents menu, and those links work fine.

Not all books have this problem, but almost all the ones I tested did have this problem. But as a counterexample, "Don Quixote" from the open-access collection on Open Ebooks works.

**Comment by winniequinn** [comment]
This likely has been fixed by now as most of the logic related to this has been replaced.
