### ISSUE TITLE
Allow user to sign out even when deauthorization is not possible

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#318]
Presently, the application will not let the user sign out when deauthorization fails. This can be a severe error if deauthorization will never succeed due to invalid credentials (e.g. if the PIN changed, the library card expired, et cetera). Even deleting the app and reinstalling it will not fix the issue because the credentials are stored in the keychain.

**Comment by aferditamuriqi** [comment]
closing, covered in #441
