### ISSUE TITLE
Replace NYPLBook, NYPLBookRegistry, and related classes

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#350]
`NYPLBook` is the essential atom of the whole application in a sense. It holds all of the information related to a particular book. `NYPLBookRegistry` is the central repository for all of that crucial information. There are also other classes, such as `NYPLBookAcquistion`, that hold portions of what makes up a single `NYPLBook`.

Unfortunately, due to what seems to be some half-finished work, things are in a bit of a state of disrepair. For example, indirect acquisitions are not adequately represented, what was previously iron-clad null checking has decayed, serialization and deserialization routines are no longer in sync, and so on.

The current state of things is not unsalvageable, but given how crucial the core models are to the app, I think it makes sense to rewrite this portion of the app in Swift and make use of its safety features such as optional tracking, generics, and so on. This would also be a good time to consider breaking out the data into multiple JSON files to avoid keeping the entire set of metadata in memory as is done presently.

**Comment by gioneill** [comment]
@winniequinn Is this still relevant?
