### ISSUE TITLE
Indicate current chapter in TOC

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#356]

**Comment by aferditamuriqi** [comment]
this could be implemented as part of https://github.com/NYPL-Simplified/Simplified/issues/23
<img src="https://cloud.githubusercontent.com/assets/17150623/23655483/85e2a94e-0363-11e7-940c-f7ed35865e94.png" width="240px"/>

**Comment by aferditamuriqi** [comment]
referencing https://github.com/NYPL-Simplified/Simplified/issues/23
