### ISSUE TITLE
Make use of total entry count in feeds to provide smoother UI

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#422]

**Comment by winniequinn** [comment]
To provide more detail on this one, the idea is to use the count in the feed to set the correct scroll length right at the very start. This would stop users from repeatedly bumping into the current bottom of the scroll view when quickly scrolling down while books are still loading. This is definitely a very low-priority issue.

**Comment by gioneill** [comment]
Will not fix.
