### ISSUE TITLE
Progress bar display is inconsistent

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#434]
Report from SimplyE patron:

_the progress bar on the iPad is wonky and doesn't always show up. Sometimes it will appear when you go to the next page. But not always. And when it does appear the accompanying text marker just says "Page 3 of 3 (Chapter)" which actually seeming to either a page count or even to indicate the chapter._

**Comment by winniequinn** [comment]
This will be fixed with the new renderer. Closing.
