### ISSUE TITLE
All books render as error message and raw CSS 

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#438]
Patron reports:

_Every time I open an ebook using the NYPL app, I can see the title pages and table of contents, but each page of text looks exactly like the attached photo-- an error message. It is the same across multiple books._

```
Device Information:
iPhone
iOS 8.1.3

App information:
org.nypl.labs.SimplyE
Version 1.0.1
```

**Comment by winniequinn** [comment]
I can't reproduce this, I'm afraid.
