### ISSUE TITLE
Authentication and credential requests to the user should be centralized

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#440]
See #430 for more information and the rationale.

**Comment by aferditamuriqi** [comment]
@winniequinn  i am not sure if this is still an issue, and if so i am maybe not understanding what should be done here.

**Comment by winniequinn** [comment]
This is probably all void now that multi-library has gone in.

**Comment by aferditamuriqi** [comment]
I am closing this
