### ISSUE TITLE
Allow users to add additional Adobe accounts

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#448]

**Comment by gioneill** [comment]
We should update this ticket now to fit into the context of how the multi-library release will handle adobe accounts.

**Comment by winniequinn** [comment]
Given how complicated things are already getting with multi-library, I have no idea if this is still on the roadmap. Personally, I'd like to see support for multiple library cards per library before we start worrying about additional Adobe accounts. I doubt many SimplyE adopters would need such a feature after the first month or so of using the app.

Thoughts, @jce1028?

**Comment by winniequinn** [comment]
I don't see us ever doing this one, thankfully!
