### ISSUE TITLE
Allow app to be used without network connection

### ISSUE THREAD

**Issue by jce1028** [NYPL-Simplified/Simplified-iOS#451]
Currently, when a user gets onto a subway then opens the app, it attempts to synch the bookshelf. This prohibits the user accessing the books they have alread stored locally.

**Comment by winniequinn** [comment]
Hm! This should definitely not be happening. I'll give it a look.

**Comment by winniequinn** [comment]
@jce1028 Are you sure this is an iOS and not an Android issue? I only know of this happening on Android.
