### ISSUE TITLE
Words reflow to different pages on page turn

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#454]
Patron report:

Today the words started moving as I turn pages. See example attached. Last words on the page were "observation by", and I turn the page. The next words don't make sense, so I return to the previous page, and see 3 new lines of text below " observation by". This kept happening so long that I stopped reading- too distracting.

**Comment by leonardr** [comment]
![image1](https://cloud.githubusercontent.com/assets/662474/17976330/0056b28e-6abb-11e6-9f33-8bdc7381ff26.PNG)
![image1 1](https://cloud.githubusercontent.com/assets/662474/17976331/0057801a-6abb-11e6-9a55-e0afd1db193e.PNG)
![img_1625](https://cloud.githubusercontent.com/assets/662474/17976332/005a5d62-6abb-11e6-8b86-c5905187f958.PNG)

**Comment by leonardr** [comment]
Judging from content, this book is "From Gutenberg to Zuckerberg: Disruptive Innovation in the Age of the Internet" by John Naughton

**Comment by winniequinn** [comment]
This is a known issue with Readium. There's not much we can do about this for the time being.

**Comment by leonardr** [comment]
Can you link this issue to the Readium issue so we don't lose track of it?

**Comment by winniequinn** [comment]
There are a number of issues related to pagination, issued with accumulated errors, multi-column layout problems, et cetera. This is going to get fixed only when we rewrite it, I think. I did check for an issue to link to but so many vaguely apply that I'm not sure it would be helpful.
