### ISSUE TITLE
Add support for building with Xcode 8

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#458]

**Comment by winniequinn** [comment]
This is almost done in the `xcode8-compatibility` branch. The main issue remaining is that DRM does not seem to work in the simulator when building with Xcode 8 (although it _does_ work on a device).

**Comment by aferditamuriqi** [comment]
implemented in https://github.com/NYPL-Simplified/Simplified-iOS/tree/pre_multi_library and https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
