### ISSUE TITLE
Certain paginated OPDS feeds just don't render

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#460]
Patron report:  'If I try to look at the Fantasy or Adventure sections, I get a "failed to connect" error. I can look at single books on the front page but not browse by category... this happens on both of my iPads.'

Some genres work, some don't. Which genres are broken changes over time. This is not a problem on Android. This indicates a problem parsing certain OPDS feeds. As books go in and out of availability, they enter and leave the first page, causing the problem to recur or go away.

**Comment by winniequinn** [comment]
I suspect this is a case of iOS being pickier than Android when it comes to data validation.

**Comment by winniequinn** [comment]
Fixed in 9a25c270d3266b160f2701f456b22e185600ce8f.
