### ISSUE TITLE
Downloaded book acts like partially buffered streaming book

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#464]
Patron report, key section highlighted:

I seem to be expiring difficulty consistently when reading a downloaded ebook on my ipad or iphone. When I first download the book, all is good on the first reading. As soon as I stop reading and put the ebook down leave for an hour, or a day, then pick up the ebook again on my ipad or iphone, _a few pages are there, but then it is completely blank_. I have to go back to the my book section, hit the book icon I am reading, then hit read, wait for the book to re-download for me to continue reading. This is a problem if I am on a plane or a subway as there is no internet connection.

Is there a way for the book to stay downloaded on my ipad or iphone until it expires? I have the most recently ipad technology, and I am working on a iphone 6S and ipad air, last year's model(2015)

**Comment by leonardr** [comment]
Patron confirms that this happens for all their books.

**Comment by aslagle** [comment]
This sounds like a misinterpretation of the chapter boundary issue.

**Comment by aferditamuriqi** [comment]
can we test this on the multi library version? i believe we have fixed this in multi library, almost sure about it actually.

**Comment by winniequinn** [comment]
I can't make much sense of this one, but I suspect this issue refers to something that was fixed at some point.
