### ISSUE TITLE
Pressing "Get" can quietly place a hold if feed is out of date

### ISSUE THREAD

**Issue by winniequinn** [NYPL-Simplified/Simplified-iOS#469]
Due to caching on the server, the app will sometimes present a "Get" button when a book is not actually available. Pressing it will place a hold which is fine, but some kind of alert should be presented so the user isn't surprised by the fact that the intended action did not happen. 

This may also pertain to Android.

**Comment by gioneill** [comment]
In my own experience, I had to try and checkout the first seven books in "Staff Picks" before being able to check out a book that was actually available. I would question the overall value of "this book is available to borrow" depending on how many titles a user attempts to borrow just to end up falling to a multi-week reserve.

**Comment by gioneill** [comment]
Will not fix.
