### ISSUE TITLE
Add setting to show the iOS status bar while in the reader

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/Simplified-iOS#470]

**Comment by aslagle** [comment]
@aferditamuriqi and I discussed this and agreed that it would be fine to instead fix the top and bottom margins so that the navigation bar doesn't cover any of the content. This way you could tap to bring up the navigation bar and then leave it up the whole time you were reading. That's what iBooks does.

**Comment by gioneill** [comment]
Here's a run-through at different text sizes. @aslagle is also trying it out over the weekend to read with. It definitely makes the reading experience better when the navigation is visible. I'm wondering how best to balance the white space when the navigation is hidden.

![screen shot 2017-03-17 at 5 20 39 pm](https://cloud.githubusercontent.com/assets/6179695/24063495/5224d318-0b36-11e7-8241-72f6399c560d.png)


iBooks:
![img_2502](https://cloud.githubusercontent.com/assets/6179695/24063470/30846516-0b36-11e7-9803-1df0a5b4a782.PNG)

**Comment by winniequinn** [comment]
As per the Slack discussion, I think this is a good idea _if and only if_ we also make use of the space when the navigation is hidden as in iBooks. The chapter title up top and the page number (and possibly a minimal progress bar) on the bottom would be fantastic!

**Comment by gioneill** [comment]
Mimicking iBooks.. with light gray/dark gray treatments for the three reading modes:
![header footer final 4](https://cloud.githubusercontent.com/assets/6179695/24124589/d28b0fe8-0d9a-11e7-9d61-1c66645b244f.png)
![header footer final 3](https://cloud.githubusercontent.com/assets/6179695/24124590/d28c27f2-0d9a-11e7-8752-73b28068ecf8.png)

**Comment by aslagle** [comment]
When the navigation is visible, using the TOC or a link in the text shouldn't hide it.

**Comment by gioneill** [comment]
@aslagle Winnie and I looked at this for a bit and have found inconsistent behavior when tapping through links in the app (sometimes it works as expected). I've created Issue #576 for this.

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
