### ISSUE TITLE
Add missing localized strings

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/Simplified-iOS#482]

**Comment by swandog30** [comment]
Does this refer to adding missing strings for Italian, German, and Spanish in Localizable.Strings?  Or to convert to NSLocalizedString where it currently isn't being used?

**Comment by aferditamuriqi** [comment]
It refers to converting to NSLicaluzedStrimg where it currently isn't being used.

**Comment by aferditamuriqi** [comment]
has been merged https://github.com/NYPL-Simplified/Simplified-iOS/pull/628 , closing this issue
