### ISSUE TITLE
Add App Icon to 'About' section in Settings

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#487]
Create a nice-looking Header Image (app icon) and Title for the About page similar to here:
![img_2047](https://cloud.githubusercontent.com/assets/6179695/19947817/316cb576-a120-11e6-861d-f48f573f4b5f.PNG)
Certain Challenges:
- Using UIWebView to get a reference to the app icon, while still respecting the unique icon of each platform
- Being efficient when considering how these pages are pulled from a remote server (with a local fallback)

**Comment by gioneill** [comment]
Uploaded the SVG Loog with transparency so it looks correct for both Android and iOS.

![screen shot 2017-04-06 at 5 04 56 pm](https://cloud.githubusercontent.com/assets/6179695/24775588/8b881b3c-1aeb-11e7-9865-eb203c07159a.png)

**Comment by aferditamuriqi** [comment]
This has been closed in 2.0
