### ISSUE TITLE
Bug with Book Reservations when switching between accounts

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#508]
The user has signed in to two accounts (BK and NYPL but using same username/password for both).

Switching back and forth, when you have books on reserve, the titles will copy themselves from one account to the other. If you try and remove a reservation on one account, it will still show as being reserved on the other account.

If you are on the Reservations tab, you also have to pull-to-refresh after switching in order to see the list of books.

For loaned books, if you try and download one that you checked out from the other account, it will give an error that it is "already fulfilled by a different user" which may point to something with device activation.

If you log out and log back in, it will work as expected to download the book.

**Comment by aferditamuriqi** [comment]
resolved in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
