### ISSUE TITLE
"chapter" word

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/Simplified-iOS#510]
in russian language, bottom of book page says: "Page 12 of 15 (chapter)".  In English version, instead of seeing the word "chapter" here, I see the name of the actual chapter.

**Comment by daryanypl** [comment]
![img_20161108_075709806](https://cloud.githubusercontent.com/assets/18293410/21023106/1d3d2c68-bd4d-11e6-9f12-6a857cc9454a.jpg)

**Comment by aferditamuriqi** [comment]
@daryanypl the chapter name will show wherever there is a chapter name available, otherwise it will show "chapter". but there is a different issue in which we need to address this anyways.  so i am referencing it here https://github.com/NYPL-Simplified/Simplified-iOS/issues/357

**Comment by gioneill** [comment]
Will not fix. Address with re-localization.
