### ISSUE TITLE
settings menu words need translation hooks

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/Simplified-iOS#513]
iOS app, in Russian version, I see untranslated: "Library Card", "Help", "About", and "Software Licenses".

![img_20161108_080952550](https://cloud.githubusercontent.com/assets/18293410/21448210/f5f0934a-c8ad-11e6-84ed-65fdc91e3028.jpg)

**Comment by gioneill** [comment]
Will not fix. Address with re-localization.
