### ISSUE TITLE
double dialog message and need translation hook

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/Simplified-iOS#514]
The error message says "cannot connect" in identical language in both the top and middle lines.
The Reload button needs a translation hook.

![img_20161108_081052119](https://cloud.githubusercontent.com/assets/18293410/21448265/9c6e046e-c8ae-11e6-9a0c-da0a7843f48a.jpg)

**Comment by gioneill** [comment]
Will not fix. Address with re-localization.
