### ISSUE TITLE
Open Search Description formatting (iOS/Android)

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#517]
When the mobile clients (android and iOS) try and request the Open Search Description from the server, the "template" link is expected to be the full search URL:
` <Url type="application/atom+xml;profile=opds-catalog" template="https://circulation.librarysimplified.org/search/?q={searchTerms}"/>`
and not:
`<Url type="application/atom+xml;profile=opds-catalog" template="?q={searchTerms}"/>`

**Comment by courte** [comment]
I believe @aslagle took care of this (with respect to Instant Classics) with NYPL-Simplified/open-search-lambda#3.

**Comment by aslagle** [comment]
I did, but the mobile clients should be able to handle relative urls. There might be a separate issue for that.

**Comment by gioneill** [comment]
Thanks for following up. This has been resolved for the open search description by updating Instant Classics. Future client work to handle relative links across the app is referenced in #358
