### ISSUE TITLE
Audit Multi-Library Features for accessibility

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#519]
Going through new UI and making sure content has been made accessible.

**Comment by gioneill** [comment]
Results from audit:

Updates needed:
- labeling and context for the new library switcher icon
- labeling and the context for the new EULA checkbox (which definitely could have caused some user frustrations while trying to sign in)

Cleared:
New Welcome Screen is good
Card Creator is good
License Screens are good (even works with voiceover on web text)
New Settings tabs are good

**Comment by aferditamuriqi** [comment]
resolved in PR #520
