### ISSUE TITLE
Send name to card creator in "last, first middle" format

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#521]
I believe this is an issue on both iOS and Android.

When gathering information to send to the card creator, the patron's name is gathered in three parts: first, middle, last. This information is sent to the server as "first middle last". But we need to store it in the ILS as "last, first middle".

Deriving "last, first middle" from "first middle last"  is basically impossible. But you have the ability to send the server the data it needs in the first place, and save the server from having to try to fix it.

**Comment by aferditamuriqi** [comment]
resolved in PR https://github.com/NYPL-Simplified/CardCreator-iOS/pull/6

**Comment by courte** [comment]
@aferditamuriqi Is this resolved in Android or can I make a separate issue for it?

**Comment by aferditamuriqi** [comment]
@courte yes it is also resolved in Android.
