### ISSUE TITLE
Remove Alamofire from Simplified-iOS

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#524]
Remove AF and replace with standard URL Session methods. We want to maintain full compatibility with iOS 8, and AF 4.0 running Swift 3 only supports 9 and higher.

- Will need new reachability class when that gets implemented as part of the queueing system.
- Replace in Analytics
- Replace in Annotations

**Comment by aferditamuriqi** [comment]
resolved in PR #525
