### ISSUE TITLE
"Connection failed" but only when running a search

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#538]
Two patrons have reported this problem on iOS. Of the two, I have specific iOS version for one: iPad 9.3.5.

Patron reports the "connection failed" message when running a search. Text searched for does not seem to matter (this makes it different from the previously fixed "connection failed" message on search). 

Specific searches tried were "jones" and "new york". I don't see any records of recent searches for these terms in the logs.

All other functionality works fine--patron can borrow and read a book. Just no search.

**Comment by winniequinn** [comment]
I believe this was fixed by @aferditamuriqi in 6b272d9d76b8a63e791ea810d559967f3aada045. Please close this if that is true, Aferdita!
