### ISSUE TITLE
Implement Report a Problem email composer

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/Simplified-iOS#540]
<img src="https://cloud.githubusercontent.com/assets/17150623/22526657/186848a8-e89a-11e6-8371-3d66ef75f820.png" width="200"/> <img src="https://cloud.githubusercontent.com/assets/17150623/22526658/186e4168-e89a-11e6-9812-f45c8ed3780d.png" width="200"/> <img src="https://cloud.githubusercontent.com/assets/17150623/22526659/186f60c0-e89a-11e6-84c2-6d69f6282136.png" width="200"/>

Depending on the type selected either send a problem report or compose an email to a given support email address

**Comment by winniequinn** [comment]
Can we use a standard `MFMailComposeViewController` for this?

**Comment by aferditamuriqi** [comment]
@winniequinn yes that is whats going to be used, if an actual email will be generated, that depends on the type of issue being selected. this screens are still going to happen before the email composer is to be triggered.

**Comment by aferditamuriqi** [comment]
added email composer to report an issue in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop under accounts detail
