### ISSUE TITLE
Support reading on an upside-down device

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#552]
Patron request, affects both Android and iOS.

Device can be used in its 'normal' portrait orientation, and in the landscape orientations 90 degrees or 270 degrees away from the 'normal' orientation, but not in the portrait orientation 180 degrees away from 'normal' orientation. (i.e. with the device upside-down and the buttons on the top).

Patron says this is an easier position to hold a device in while in bed.

**Comment by winniequinn** [comment]
This is the standard behavior for iPhone applications and should not be changed. I'll confirm iPad can be used upside-down as intended and will reopen if necessary, but I am pretty sure everything is as it should be.

**Comment by leonardr** [comment]
Please don't close an issue with the intention to reopen later after doing some more checking. That's how things slip through the cracks. Do the checking first.

Aferdita has confirmed that iPad cannot be used upside-down. As such I'm reopening the issue.

**Comment by winniequinn** [comment]
It seems this does not work on iPad as intended. I'll put a fix in shortly.
