### ISSUE TITLE
Increase maximum possible font size

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#560]
Patron reports that the largest selectable font size is still too small for them to read.

If this were to be changed it would have an iOS component and an Android component.

**Comment by gioneill** [comment]
To address font size issue from the patron I've created one extra "size" in the spectrum for eight total:

    case NYPLReaderSettingsFontSizeSmallest: 70;
    case NYPLReaderSettingsFontSizeSmaller: 80;
    case NYPLReaderSettingsFontSizeSmall: 90;
    case NYPLReaderSettingsFontSizeNormal: 100;
    case NYPLReaderSettingsFontSizeLarge: 120;
    case NYPLReaderSettingsFontSizeXLarge: 150;
    case NYPLReaderSettingsFontSizeXXLarge: 200;
    case NYPLReaderSettingsFontSizeXXXLarge: 220;

But another possible way to address it would be to just increase the size of the largest setting without adding an extra. And also the question of how much to actually increase it.

**Comment by winniequinn** [comment]
220 doesn't seem too much larger than 200. Maybe do 250 instead? I think the general approach is good in any case!

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
