### ISSUE TITLE
subtitle on account list is truncated, update label to support multiple lines 

### ISSUE THREAD

**Issue by aferditamuriqi** [NYPL-Simplified/Simplified-iOS#564]

**Comment by gioneill** [comment]
The cell labels now fully support dynamic heights. For longer descriptions the cell will grow to accommodate. The NYPL description is too long for two lines on most iPhones, so it expands to three in this case.

This also paves the way for supporting Dynamic Type and making our app fully accessible to users who select a larger font that they can read legibly. This can be accomplished piecemeal over time.

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
