### ISSUE TITLE
Reader - Single Tap For Links - Inconsistent Behavior

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#576]
When a user taps on some kind of link in a book, they should be taken through to the destination with the navigation UI remaining _consistent_ before and after.

In some instances this works as expected: Navigating a table of contents inside a book, and tapping a chapter takes a user to that page and keeps the nav hidden or shown consistently.

In other instances, tapping links (like endnotes) toggles the navigation to show/hide, requiring the user to tap again somewhere on the page to toggle it back.

Example of TOC: Make Me - Lee Child (Overdrive)
Example of endnotes: Twenty Thousand Leagues Under the Seas (Standard Ebooks)

**Comment by winniequinn** [comment]
As we discussed, the current approach to tap detection is not correct. If the issue is not too prevalent, I would be okay with leaving it as-is because we'll be replacing it come Readium 2.x anyway.
