### ISSUE TITLE
Add UIWhitePointAdaptivityStyle key for True Tone Displays

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#578]
Came across this, and seems like an easy win:

> The True Tone display uses ambient light sensors to automatically adjust the color and intensity of the display to match the lighting conditions of the current environment. To ensure that your app works well with the standard color shift provided by True Tone, add the new UIWhitePointAdaptivityStyle key to your Info.plist file to describe your app’s primary visual content. For example:
    * If your app is a reading app, conformance with the environmental white point is helpful to users. In this case, you can use the UIWhitePointAdaptivityStyleReading style to increase the strength of True Tone shift applied by the system.

**Comment by aferditamuriqi** [comment]
currently this is only a feature of the 9.7" iPad Pro

**Comment by winniequinn** [comment]
This has been done.
