### ISSUE TITLE
Links not opening externally for license pages

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#585]
1. Fix link to Privacy Policy
2. Make sure links (for sites or "mailto:" etc.) take the user to safari/appropriate destination.

![image_uploaded_from_ios_480](https://cloud.githubusercontent.com/assets/6179695/24477197/2f70ad5c-14a4-11e7-83a7-44906efaef04.jpg)

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/NYPL-Simplified/Simplified-iOS/tree/multi_library_develop
