### ISSUE TITLE
Save Reader Settings when closing book

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#603]
The reader settings ([NYPLReaderSettings sharedSettings]) should be saved when leaving the current book in order to persist changes from book to book.

Currently it only saves when the app suspends or terminates.
The changes may persist in memory, but are only written locally to settings.json on suspend or terminate.

**Comment by aferditamuriqi** [comment]
please also take a look into NYPLBookRegistry and determine if a save is being done at the right time.

**Comment by gioneill** [comment]
Moving to 2.2.0 so I can also test with the update to readium-shared-js
