### ISSUE TITLE
app should display the reading location relative to the entire book

### ISSUE THREAD

**Issue by mgiraldo** [NYPL-Simplified/Simplified-iOS#620]
not only in the current chapter

**Comment by winniequinn** [comment]
This is not possible at the moment. It may happen down the road when the new renderer goes in.

**Comment by mgiraldo** [comment]
with @courte we were discussing dealing with this server-side

**Comment by winniequinn** [comment]
A change has gone in for this on Android:

https://github.com/NYPL-Simplified/android/pull/488

**Comment by winniequinn** [comment]
Obsoleted by #667.
