### ISSUE TITLE
readium-sdk submodule remote URL appears out of date

### ISSUE THREAD

**Issue by datalogics-cgreen** [NYPL-Simplified/Simplified-iOS#649]
When I clone a new repo, switch to the develop branch, and run `git submodule update --init --recursive`, I get this error:

```
Fetched in submodule path 'readium-sdk', but it did not contain 1a39de550ddf6876c9a06358bbe1649d39199195. Direct fetching of that commit failed.
```

.gitmodules currently points to `git@github.com:NYPL/readium-sdk.git`, but I believe it should be `git@github.com:NYPL-Simplified/readium-sdk.git`

**Comment by winniequinn** [comment]
I am seeing this as well, although I don't think URL is the issue: The former should be redirecting to the latter just fine. I'll see if I can't get this resolved ASAP.

**Comment by winniequinn** [comment]
The missing commit was restored to `NYPL-Simplified/readium-sdk` on the `feature/drm` branch.
