### ISSUE TITLE
BS Bug: touch intersect methods in reading view

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#670]
[Bugsnag Link](https://app.bugsnag.com/nypl-1/android-open-ebooks/errors/596afce4a206840018738f75?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&filters%5Bversion.introduced_in%5D%5B%5D%5Bvalue%5D=2.0.3&filters%5Bversion.introduced_in%5D%5B%5D%5Btype%5D=eq)

One thing to note:
- It seems like all of these users have spent significant (> 1 hr) time in the app before hitting this crash! Our most loyal readers will enjoy having this one solved 👍 
- I was seeing both the gesture recognizer and the touchIntersects methods get called together usually only with a right->left swipe from the center of the screen, NOT a swipe that initiates the page curl animation.. there seem to be three unique types: just a touch, a swipe from somewhere in the middle, and a slow swipe from the very right edge.

**Comment by gioneill** [comment]
After looking at the history of this bug, it's very clear that it was introduced on 4/13/2017 as part of 2.0.0:

![bug_analysis](https://user-images.githubusercontent.com/6179695/28790831-7ea75bae-75f8-11e7-845f-6f2eaee7086d.png)

So I went ahead and looked at the diff's as far back as 11/1/2016, when the first commit after v1.0.3 was tagged. First interesting point: Between then and now there were **NO** changes to the two methods (touchIntersectsLink and gestureRecognzier) pointed at in the stack trace. Fully reviewing the two classes shows, however, a different change that _may_ have an effect:

in commit 21f1822 of NYPLReaderReadiumView.m
`  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
`
The delay was reduced from 3 sec to 0.5 sec for each page turn.

At the worst case of not having a specific problem to point to, I'm willing to increase this and look at the effect over the course of a few days with data-gathering.

**Comment by gioneill** [comment]
This issue has been linked to an error in Bugsnag
[**EXC_BAD_ACCESS** in **NYPLReaderReadiumView**](https://app.bugsnag.com/nypl-1/ios-simplified/errors/59791de00c52350018d16adc?event_id=5982a9fcbea2c9001ac4085f&i=gh&m=li)

**Comment by winniequinn** [comment]
Really good work on this, @gioneill! I will give it a look as soon as I get through my current set of tasks.
