### ISSUE TITLE
iOS11: System fonts in app no longer overriding to custom font

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#710]
Our original solution, which was to [override the default implementations](https://stackoverflow.com/a/17977354/3499815) of the system font class, is no longer working for system-level areas of the app like navigation controller titles and tab bar icons.

Will need to find a new way to carry a custom font choice to all the UI inside SimplyE.

https://github.com/NYPL-Simplified/Simplified-iOS/blob/12d13c4d23125e17f82eae22dd2761b2448ec237/Simplified/UIFont%2BNYPLSystemFontOverride.m#L5-L16

**Comment by winniequinn** [comment]
@gioneill I talked this over with @jce1028 recently and we're both okay with simply using the default system font instead of Avenir. That would make "fixing" this a lot easier!
