### ISSUE TITLE
Impossible to log in with non-alphanumeric character in passcode 

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#717]
There's a test user with the Alameda County Library who has a non-alphanumeric character in their passcode. I'll send Greg this user's credentials privately.

It's possible to go directly against Alameda's circ manager and use these credentials to get the loans feed, but it's not possible to log in to SimplyE using the same credentials. My best guess is that the non-alphanumeric character is causing the problem. Up to this point we haven't had a situation where a user's passcode could contain non-alphanumerics.

I have confirmed this problem on iOS but have not checked Android.

**Comment by gioneill** [comment]
I just tested on the latest beta and it looks good, but it took a couple tries. It's also very possible the tester did not update to the latest beta in TestFlight.

Have the user first check if they're on the latest beta, and then report back on what type of error message they're receiving if it still fails.

![screen shot 2017-08-25 at 4 38 04 pm](https://user-images.githubusercontent.com/6179695/29731830-10e9c23a-89b4-11e7-8653-663e48293eb7.png)
![screen shot 2017-08-25 at 4 37 55 pm](https://user-images.githubusercontent.com/6179695/29731831-10eced02-89b4-11e7-823b-c251dc6e2d32.png)

**Comment by leonardr** [comment]
I'm closing the issue and will reopen if the problem resurfaces.
