### ISSUE TITLE
Handling gzip .epub's over the network

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#765]
I have a feeling that NSURLSession just doesn't like gzip'ed epubs but I can't think of an easy way to get to the bottom of this. One note is that this download link seems to work in specific readers, but fails cryptically in safari and chrome. The downloads do work on Android.

I see virtually nothing in our `downloadTask` that would affect this. We're not customizing any system defaults, and the delegate sends standard basic auth. So while I'm pretty confident there's nothing on the client that would fix this, I also don't have an adequete explanation as to why. 

```Greg O'Neill
[3:21 PM] 
http://50.112.147.80/XXTEST/works/2/fulfill/1

Leonard Richardson [3:23 PM] 
ok i did `$ curl -I http://21157021878627:Test@50.112.147.80/XXTEST/works/2/fulfill/1`

[3:23] 
that shows the headers

[3:24] 
HTTP/1.1 200 OK
Content-Type: application/epub+zip;
Content-Length: 49271
Connection: keep-alive
Content-Disposition: attachment; filename="9780231133821.epub"
X-Powered-By: PHP/5.3.22
Set-Cookie: test_ip=50.112.147.80; path=/, branch=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/, PHPSESSID=t6v2qjhpiuaqfgn0v90ohhmrd7; path=/, ui=standard; path=/
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Vary: Accept-Encoding
Server: Apache/2.2.29 (CentOS)
Content-Description: The Art of War
Pragma: no-cache
Cache-Control: no-cache, must-revalidate
Date: Wed, 30 Aug 2017 19:23:24 GMT
Content-Encoding: gzip

[3:24] 
that looks fine

[3:24] 
then i downloaded the EPUB to a file and was able to open it in a viewer

[3:24] 
`curl http://21157021878627:Test@50.112.147.80/XXTEST/works/2/fulfill/1 > war.epub`

[3:2] 
oh, wait

[3:25] 
`Content-Type: application/epub+zip;`

Greg O'Neill [3:25 PM] 
ok let me do a little digging on the download and we'll come back to the checking in part if there's time

Leonard Richardson
[3:25 PM] 
that's wrong. you only check for `Content-Type: application/epub+zip`

[3:25] 
`application/epub+zip;` isn't incorrect

[3:25] 
it's unusual but valid

[3:25] 
it's saying there are no parameters on the media type

[3:26] 
i usually check whether the media type starts with the thing i'm looking for, because of parameters

Greg O'Neill [3:37 PM] 
>The connection cannot decode data encoded with a known content encoding.
Does that seem like it would be causing the download to fail?

Leonard Richardson
[3:37 PM] 
sure

[3:37] 
maybe it can't handle a gzipped epub?```

**Comment by winniequinn** [comment]
Just to be clear, `application/epub+zip` is the standard MIME type for EPUBs. I don't think there's anything usual about that part.

While the test URL @leonardr was using no longer seems to work, the "cannot decode data encoded with a known content encoding" error @gioneill shared makes me think that the server is sending `Content-Encoding: gzip` but the data is not actually gzipped. It's very likely that cURL is more forgiving about this sort of thing than `NSURLSession`. 

Can we try looking at the data the server is sending to confirm it's actually gzipped? Alternatively, can we drop the header without changing the data stream and see if everything suddenly works?

**Comment by winniequinn** [comment]
This has been resolved with a server-side fix.
