### ISSUE TITLE
Compilation error regarding SQLite.swift

### ISSUE THREAD

**Issue by Raymond26** [NYPL-Simplified/Simplified-iOS#773]
I'm getting the following error when trying to compile when following the Build Without DRM instructions:

<img width="842" alt="screen shot 2017-09-26 at 6 26 26 pm" src="https://user-images.githubusercontent.com/885279/30891454-50bf8d70-a2e8-11e7-926b-4ffb72ee6ae9.png">

Is there a specific Swift version i should be using?  I am on XCode 8.3.3 Swift 3.1 

When I did the `pod install` it recommended I do `pod install --repo-update` so when I did that, this is what was installed:

<img width="808" alt="screen shot 2017-09-26 at 6 28 35 pm" src="https://user-images.githubusercontent.com/885279/30891549-d55a67e4-a2e8-11e7-9399-17ce4915dab4.png">

**Comment by gioneill** [comment]
Ah! Yes you should be using the latest Xcode, which is actually Xcode 9 (with Swift 4). We had to update and fork the SQLite dependency to work on the latest IDE. So it won't work on older versions now.

Update Xcode. Clean the project, run `pod install` again in the directory, then try and rebuild and let me know if everythings okay.

**Comment by Raymond26** [comment]
Thanks for the help!  Updating solved the SQLite issues.  Dealing with an issue around NYPLADEPT

![screen shot 2017-09-29 at 1 09 45 am](https://user-images.githubusercontent.com/885279/31006754-eb228e6e-a4b2-11e7-9872-80c38c24f144.png)

**Comment by gioneill** [comment]
If you've removed the libraries in the build settings, which is mentioned in readme, there's one or two other files you'll also need to remove in the project navigator pane on the left side. I don't remember them off the top of my head but they're related to adept.

**Comment by gioneill** [comment]
OKAY so actually I forgot to protect this function around a check for DRM, so it's my fault! BUT you may not have performed the above step yet so I'll keep that comment there.

I've pushed that commit, so pull the latest down from Master.

**Comment by Raymond26** [comment]
Thanks so much! I pulled the latest from Master and that seemed to do the trick.  For some reason, I didn't have the `Simplified+RMSDK.xcconfig` in my directory
