### ISSUE TITLE
Handle abbreviated URLs in OPDS feeds

### ISSUE THREAD

**Issue by ghost** [NYPL-Simplified/Simplified-iOS#79]
Currently, the client is able to handle links such as the following:

```
<link rel="http://opds-spec.org/facet" 
      href="http://example.com/sci-fi" 
      title="Science-Fiction" 
      opds:facetGroup="Categories" 
      opds:activeFacet="true" />
```

It cannot, however, handle an `href` like the following where the scheme and domain are missing:

```
<link rel="http://opds-spec.org/facet" 
      href="/sci-fi" 
      title="Science-Fiction" 
      opds:facetGroup="Categories" 
      opds:activeFacet="true" />
```

The server currently always includes the scheme and domain, so this doesn't actually cause us any problems. It would be nice, however, if we did handle such things properly as it's technically required by the OPDS spec:

```
atomUri = xsd:anyURI - xsd:string {pattern = '.*[ <>{}|^`"\nrt].*'}
```

**Comment by winniequinn** [comment]
Obsoleted by #358.
