### ISSUE TITLE
"CRASHING_DUE_TO_PRIVACY_VIOLATION"

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#845]
## Error in iOS - Simplified

**SIGABRT** in **___CRASHING_DUE_TO_PRIVACY_VIOLATION__**

[View on Bugsnag](https://app.bugsnag.com/nypl-1/ios-simplified/errors/59cc5aea4ada50001844b5bf?event_id=5a1f12536be2260018e4191d&i=gh&m=ci)

## Stacktrace

    /usr/lib/system/libsystem_kernel.dylib:0 - ___abort_with_payload

[View full stacktrace](https://app.bugsnag.com/nypl-1/ios-simplified/errors/59cc5aea4ada50001844b5bf?event_id=5a1f12536be2260018e4191d&i=gh&m=ci)

*Created by Gregory O'Neill via Bugsnag*

**Comment by gioneill** [comment]
I can't think of too many things we're accessing other than the camera or location services. There must be a check missing, or maybe a required description string in the Plist..

**Comment by winniequinn** [comment]
Is this still a problem, @gioneill? I think you fixed this in #892.

**Comment by gioneill** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**SIGABRT** in **___CRASHING_DUE_TO_PRIVACY_VIOLATION__**](https://app.bugsnag.com/nypl-1/ios-simplified/errors/59cc5aea4ada50001844b5bf?event_id=5a71011df5939f00188d85c7&i=gh&m=fx)

**Comment by winniequinn** [comment]
I will take that as a yes!

**Comment by gioneill** [comment]
An error linked to this issue has been reopened in Bugsnag
[**SIGABRT** in **___CRASHING_DUE_TO_PRIVACY_VIOLATION__**](https://app.bugsnag.com/nypl-1/ios-simplified/errors/59cc5aea4ada50001844b5bf?event_id=5a78517cc99358001860e09b&i=gh&m=ra)

**Comment by gioneill** [comment]
It seems as though a faulty implementation of photos access by a third party dependency means that the app needs both plist keys present:

NSPhotoLibraryUsageDescription (6.0+) AND NSPhotoLibraryAddUsageDescription (11.0+)

All users with the symptom are on iOS 11, which matches the behavior discussed here:
https://github.com/react-community/react-native-image-picker/issues/632

**Comment by gioneill** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**SIGABRT** in **___CRASHING_DUE_TO_PRIVACY_VIOLATION__**](https://app.bugsnag.com/nypl-1/ios-simplified/errors/59cc5aea4ada50001844b5bf?event_id=5abede1ffad61b001a9448eb&i=gh&m=fx)
