### ISSUE TITLE
Reader needs progress indicator + abort mechanism for excessively long loads

### ISSUE THREAD

**Issue by ghost** [NYPL-Simplified/Simplified-iOS#85]
On older devices, a complex EPUB can lock up the application for ten seconds or more. In order to make this acceptable, the reader view should show a progress indicator if it has been waiting more than a few seconds for a page load request to complete.

It should also, at some point, offer a cancel button so that the user can back out of the attempt. Poorly written JavaScript within a book can certainly hang the app forever at the moment, so some protections do need to be added.

**Comment by winniequinn** [comment]
We currently have a progress indicator and failsafes to deal with long loads.
