### ISSUE TITLE
Reader crashes shortly after opening

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#876]
I've received two support requests that seem indicative of the same problem:

"I can only read for a minute or two before the app crashes. There are no updates available and I’ve tried restarting the phone." - iOS 11.2.1, SimplyE 2.2.1.

"This book makes the app crash 2 mins after opening it up" - iOS 10.2.1, SimplyE 2.2.1, title "The Pagan Lord" (Overdrive 011ae249-e788-45dc-9a10-c817ccd6c118)

**Comment by leonardr** [comment]
Here's another one:

I can’t open my ebook
I was reading. Closed it, then went back in.
I get to a page, and it 3 seconds it shuts down.

iPad iOS 11.2.1, SimplyE 2.2.1.

**Comment by gioneill** [comment]
Already fixed and will be submitted with a handful of other bug fixes in v2.2.2 later today or tomorrow.

Patrons can be advised to either keep an eye out for the update. A temporary fix is to use the app in "airplane mode" with no network connectivity.

**Comment by leonardr** [comment]
Thanks, Greg.

**Comment by leonardr** [comment]
Can you link this issue to the original issue that tracks the problem?
