### ISSUE TITLE
SIGTRAP in SQLite.Statement.next() -> [SQLite.Binding?]?

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#897]
## Error in iOS - Simplified

**SIGTRAP** in **SQLite.Statement.next() -> [SQLite.Binding?]?**

[View on Bugsnag](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5a4f7a8156edd600189e25c4?event_id=5a65f14b70eab9001a4bc44f&i=gh&m=ci)

## Stacktrace

    Frameworks/SQLite.framework/SQLite:0 - SQLite.Statement.next() -> [SQLite.Binding?]?
    Frameworks/SQLite.framework/SQLite:0 - partial apply forwarder for closure #1 () -> SQLite.Row? in closure #2 () -> Swift.AnyIterator<SQLite.Row> in SQLite.Connection.prepare(SQLite.QueryType) throws -> Swift.AnySequence<SQLite.Row>
    Frameworks/SQLite.framework/SQLite:0 - partial apply forwarder for reabstraction thunk helper from @callee_owned () -> (@owned SQLite.Row?) to @callee_owned () -> (@out SQLite.Row?)
    Simplified/NYPLNetworkQueue.swift:0 - next
    Simplified/NYPLNetworkQueue.swift:0 - retryQueue
    Simplified/NYPLReachability.m:61 - -[NYPLReachability reachabilityChanged:]
    Simplified/NYPLReachabilityManager.m:96 - ReachabilityCallback

[View full stacktrace](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5a4f7a8156edd600189e25c4?event_id=5a65f14b70eab9001a4bc44f&i=gh&m=ci)

*Created by Gregory O'Neill via Bugsnag*

**Comment by winniequinn** [comment]
@gioneill It looks to me like the problem _may_ be that you are modifying what you are iterating over.

Here is where you begin your iteration:

https://github.com/NYPL-Simplified/Simplified-iOS/blob/aa836dca0acec1821767597dac789403337f47f6/Simplified/NYPLNetworkQueue.swift#L101-L103

When iterating, you are calling `retry`. Within `retry`, you are removing rows from the table you are iterating over:

https://github.com/NYPL-Simplified/Simplified-iOS/blob/aa836dca0acec1821767597dac789403337f47f6/Simplified/NYPLNetworkQueue.swift#L114-L118

What I would suggest instead is doing one iteration to collect the IDs of the rows you want to remove and then iterating over those IDs in a second pass to actually remove them.

Does that make any sense?

**Comment by winniequinn** [comment]
@gioneill Better idea: Before iterating, just have a single query that deletes everything that has already hit the max retry limit so the table isn't being modified during the iteration itself. Something along the lines of this should work (albeit translated into whatever the SQLite library wants):

```sql
DELETE FROM offline_queue WHERE retry_count > MaxRetriesInQueue
```
