### ISSUE TITLE
Possible error in Reservation Queue Position Values

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#922]
> Also look at the holds queue for Altered Carbon. SimplyE states #54 in line for 173 copies. Log into Overdrive ebooks.nypl.org and it states #173 on 54 copies.

Check out a few other books on Hold and see if they all give the reverse of "total" versus "position in line"

**Comment by gioneill** [comment]
These two values are read from the OPDS feed for the book entry.
For NYPL, perform a GET request to `https://circulation.librarysimplified.org/loans/` and basic auth with your library credentials.

I would check out a few Overdrive books. The content provider is stated in the metadata at the bottom of the Book Detail VC. Top Picks books usually need to be Reserved.

Class `NYPLBookDetailNormalView` handles the display and string building. It's the "messaging strip" just underneath the book covor and title.

Either I got it wrong, or Overdrive got it wrong. It's a 50/50 chance. I've also never used the web-based ebook system for Overdrive, but their books should be checked out in either direction, and should show up in either bookshelf.

**Comment by gioneill** [comment]
Actually, there's another option which I haven't thought of which is "the server got it wrong", so maybe some investigating with the implementor of ebooks.nypl.org would be warranted!

**Comment by djds23** [comment]
As a note, this string isn't even rendered on 4 inch display

<img width="216" alt="screen shot 2018-03-14 at 12 56 11 pm" src="https://user-images.githubusercontent.com/5833968/37417629-25a33118-2787-11e8-8bbf-412714c924ba.png">

there is too much text & the font is too big for the label.

I am able to reproduce this issue however with my own account.

<img width="310" alt="screen shot 2018-03-14 at 12 58 19 pm" src="https://user-images.githubusercontent.com/5833968/37417790-8a174f9e-2787-11e8-8177-19f60aebdce1.png">

**Comment by gioneill** [comment]
Good catch on the UILabel. Do you want to look at results based on changing the maximum number of lines to 3? Also open up the little accessibility pallette and try some different type sizes to see if things are still okay.
