### ISSUE TITLE
Don't show search interface when a feed is not searchable

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#939]
It's [legal](http://opds-spec.org/specs/opds-catalog-1-1-20110627/#Search) for an OPDS feed to omit  a `search` link. It's also likely to happen with increasing frequency in real collections, especially small or static collections.

When an OPDS feed does not have a `search` link, our OPDS clients should decline to show a search box. This has implications for the broader UI, especially since within a given library, some parts of the collection may be searchable and some may not.

**Comment by winniequinn** [comment]
@leonardr I believe this behavior is already the case—or at least it definitely was at one point. Have you seen otherwise?

**Comment by leonardr** [comment]
You're right, this is the behavior on iOS, but not on Android. I'll close this issue and mention this in the Android issue.
