### ISSUE TITLE
Time Remaining to Expiration of "Hold Available" not visible in download button

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#940]
There should be a clock with an expiration on a Hold that has become availabe to checkout. After the expiration, the hold goes away for that user and goes to the next patron in the queue.

This should be the same button format as the expiration on a "Currently checked out loan."

This was likely inadvertently removed when the expiration clock view was taken out of certain views.

![simulator screen shot - iphone 7 - 2018-03-19 at 10 11 43](https://user-images.githubusercontent.com/6179695/37600672-5dcc3fd2-2b5e-11e8-9827-4dcd393307ec.png)

**Comment by gioneill** [comment]
To further explain my point above, what I mean is that I updated `NYPLButton` to correctly show the view for the clock to the left of the text label. So one should refer to any buttons used on the "My Books" tab, because the format should be the same.

The fix may be obvious from the code, but getting a book into this state to actually test the result in the UI might be difficult / require some assistance from the backend, but that's the implementor's decision.

**Comment by djds23** [comment]
edit: `NYPLButton` should be `NYPLRoundedButton`

**Comment by gioneill** [comment]
The string `BookDetailViewControllerReservedTitleFormat` could be updated to provide more context. I'd consider it a closed issue by that point.

"Your reserve is available for X more days/hours/.."

As noted, the clock does show up when looking at the list view.

**Comment by djds23** [comment]
closing
