### ISSUE TITLE
Crash in NYPLZXingEncoder

### ISSUE THREAD

**Issue by gioneill** [NYPL-Simplified/Simplified-iOS#965]
## Error in iOS - Simplified

**SIGSEGV** in **NYPLZXingEncoder**
Attempted to dereference garbage pointer 0xf7792bec8.

[View on Bugsnag](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5accf0e60686b7001a466c40?event_id=5ad0d2f18216a200172d8de0&i=gh&m=ci)

## Stacktrace

    Simplified/NYPLZXingEncoder.m:23 - +[NYPLZXingEncoder encodeWithString:format:width:height:library:encodeHints:]
    Simplified/NYPLBarcode.swift:42 - image
    Simplified/NYPLBarcode.swift:0 - image
    Simplified/NYPLSettingsAccountDetailViewController.m:945 - -[NYPLSettingsAccountDetailViewController tableView:cellForRowAtIndexPath:]

[View full stacktrace](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5accf0e60686b7001a466c40?event_id=5ad0d2f18216a200172d8de0&i=gh&m=ci)

*Created by Gregory O'Neill via Bugsnag*

**Comment by gioneill** [comment]
Just to keep track of it, our intended change is referenced in an issue here:
Based on the line of failure, it's assumed that a loss of a reference to the ZXImage class is creating a garbage pointer to be used when creating the UIImage.

https://github.com/TheLevelUp/ZXingObjC/issues/146

>I think this may be due to the fact that the ZXImage isn't stored anywhere, so it gets realloced immediately, also releasing the CGImage.

The following should work better:

    ZXImage *image = [ZXImage imageWithMatrix:result];
    UIImage *img = [UIImage imageWithCGImage:image.cgimage];```

**Comment by gioneill** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**SIGSEGV** in **NYPLZXingEncoder**](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5accf0e60686b7001a466c40?event_id=5ad493db8b11a0001d4090e1&i=gh&m=fx)

**Comment by gioneill** [comment]
An error linked to this issue has been reopened in Bugsnag
[**SIGSEGV** in **NYPLZXingEncoder**](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5accf0e60686b7001a466c40?event_id=5ad8f16ff74185001850e58a&i=gh&m=ra)

**Comment by djds23** [comment]
noooo

**Comment by gioneill** [comment]
2.2.10 is currently a beta. I have two forks currently out in TestFlight. One of them had not been rebased with the XZing fix.. so I think we're good!

**Comment by gioneill** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**SIGSEGV** in **NYPLZXingEncoder**](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5accf0e60686b7001a466c40?event_id=5b00cf859ab153001c373f22&i=gh&m=fx)
