### ISSUE TITLE
App occasionally temporarily freezes when opening a book via Readium

### ISSUE THREAD

**Issue by ghost** [NYPL-Simplified/Simplified-iOS#99]
I believe this may be due to fetching external XML resources (which it shouldn't be doing). More research is required.

**Comment by aferditamuriqi** [comment]
this will be addressed when upgrading the readium-sdk to 0.25.0

**Comment by winniequinn** [comment]
This was actually fixed in NYPL-Simplified/readium-sdk@dca0d1b9530a273b49854dd6b59d397e6bb9a644, I believe. It looks like this ticket was just never closed.
